# location of the archive file and for tmp dir
dir1: /home/jakub-kali/Pulpit/logi_do_testow 
# location of uncpacked files
dir2: /home/jakub-kali/Pulpit/logi_do_testow/wypakowane 
# location for results of search
dir3: /home/jakub-kali/Pulpit/logi_do_testow/results 

phrases: # add as many as want
  - atos
  - elopak
  - paris2024


