# location of the archive file and for tmp dir
dir1: /path/to/archive
# location of uncpacked files
dir2: /path/to/unpack 
# location for results of search
dir3: /path/to/rg/results 

phrases: phrase_1|phrase_2|phrase_3 # add as many as want and separate each with |


